#!/usr/bin/env node

/*
 * NOTE: IF you get a "spawn EMFILE" error, try increasing your
 * open file descriptors limit: ulimit -n 1000
 */
var exec = require('child_process').exec
  , fs   = require('fs');

var handle_error = function(error, stderr) {
  if (stderr !== '') { console.error('stderr: ' + stderr); process.exit(1); }
  if (error !== null) { console.error('exec error: ' + error); process.exit(1); }
};

var get_gush_file = function(options, cb) {
  // Process repo's gush.json file
  exec("git cat-file -p gush_json", options, cb);
};

var main = function() {
  // Get arguments passed to script
  var options = {cwd: process.cwd()};
  get_gush_file(options, function(error, stdout, stderr) {
    handle_error(error, stderr);
    console.log(stdout);
    exec("git checkout -f master", options, function(error, stdout, stderr) {
      handle_error(error, stderr);
      console.log(stdout);
    });
  });
};
main();
